<a href="https://colab.research.google.com/github/GautamChy/Data-Science/blob/main/22_Min_max_scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Min-max scaling(rescales to a range, often 0–1) = It is  mainly used in Deep learning

*FORMULA
* x' = x - xmin / xmax - xmin

# Feature scaling
- Min-max scaling, z-score standardization, and normalization are generally considered feature scaling (a preprocessing step).

Normalization[Min Max Scaler] --> 0 to 1

Avg 24,25,26,27,28,30

Transformation --> xscaled = (x - xmin)/(xmax - xmin)

(24-24)/(30-24)

Mostly use standardization in Machine learning and normalization in deep learning.

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset('taxis')
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [ ]:
# importing MinMaxScaler from sklearn.preprocessing
from sklearn.preprocessing import MinMaxScaler

In [ ]:
min_max = MinMaxScaler()

In [ ]:
min_max

MinMaxScaler()

In [ ]:
df[['distance', 'fare', 'tip']]

      distance  fare   tip
0         1.60   7.0  2.15
1         0.79   5.0  0.00
2         1.37   7.5  2.36
3         7.70  27.0  6.15
4         2.16   9.0  1.10
...        ...   ...   ...
6428      0.75   4.5  1.06
6429     18.74  58.0  0.00
6430      4.14  16.0  0.00
6431      1.12   6.0  0.00
6432      3.85  15.0  3.36

[6433 rows x 3 columns]

In [ ]:
# Checking the max and min values of the columns. This is the original data
max(df['distance']), min(df['distance']), max(df['fare']), max(df['tip']),min(df['tip'])

(36.7, 0.0, 150.0, 33.2, 0.0)

In [ ]:
# fitting the data to the MinMaxScaler
min_max.fit(df[['distance', 'fare', 'tip']])

MinMaxScaler()

In [ ]:
# transform the data to the MinMaxScaler
min_max.transform(df[['distance', 'fare', 'tip']])

array([[0.04359673, 0.04026846, 0.06475904],
       [0.02152589, 0.02684564, 0.        ],
       [0.0373297 , 0.04362416, 0.07108434],
       ...,
       [0.11280654, 0.10067114, 0.        ],
       [0.03051771, 0.03355705, 0.        ],
       [0.10490463, 0.09395973, 0.10120482]])

In [ ]:
# fitting and transform the data to the MinMaxScaler, we did both fitting and transform at once.
min_max.fit_transform(df[['distance', 'fare', 'tip']])

array([[0.04359673, 0.04026846, 0.06475904],
       [0.02152589, 0.02684564, 0.        ],
       [0.0373297 , 0.04362416, 0.07108434],
       ...,
       [0.11280654, 0.10067114, 0.        ],
       [0.03051771, 0.03355705, 0.        ],
       [0.10490463, 0.09395973, 0.10120482]])

In [ ]:
 # take above array data which is in 2D array, and take original columns name
import pandas as pd
df = pd.DataFrame(min_max.fit_transform(df[['distance', 'fare', 'tip']]), columns=['distance', 'fare', 'tip'])
df

      distance      fare       tip
0     0.043597  0.040268  0.064759
1     0.021526  0.026846  0.000000
2     0.037330  0.043624  0.071084
3     0.209809  0.174497  0.185241
4     0.058856  0.053691  0.033133
...        ...       ...       ...
6428  0.020436  0.023490  0.031928
6429  0.510627  0.382550  0.000000
6430  0.112807  0.100671  0.000000
6431  0.030518  0.033557  0.000000
6432  0.104905  0.093960  0.101205

[6433 rows x 3 columns]

In [ ]:
df.head()

   distance      fare       tip
0  0.043597  0.040268  0.064759
1  0.021526  0.026846  0.000000
2  0.037330  0.043624  0.071084
3  0.209809  0.174497  0.185241
4  0.058856  0.053691  0.033133

In [ ]:
# Checking the max and min values of the columns. This is after Normalization data
max(df['distance']), min(df['distance']), max(df['fare']), max(df['tip']),min(df['tip'])

(1.0, 0.0, 1.0, 1.0, 0.0)