<a href="https://colab.research.google.com/github/GautamChy/Data-Science/blob/main/24_Data_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Types of data in statistics ( search on google 'types of data in statistics' )
# Scales of data
* nomial data, ordinal data,interval data, ratio data

# Note:
* search on google "attention is all you need.com"
and see view pdf and read all to know about more data encodig.

| Experience (years)    | Education | Salary  |
|----------|-----|--------|
| 4   | BE  | 50000 |
| 6      | Phd  | 100000 |
| 3  | Master  | 80000 |
| 6  | Phd     | 120000

Experience and Education are the input or independent features and Salary is output or dependent features or target

Education is categorical feature. if we give the education in model then model can't understand the data because inside education data is in character but model  understand only numerical value.

The main aim of data encodingis to convert categorical feature into numerical feature so that machine learning model can be trained.

Types of Data Encoding
* 1 ) One Hot Encoding
* 2 ) Label Encoding
* 3 ) Target Guided Ordinal Encoding

# 1) Nominal or One Hot Encoding(No specific order or rank)

House Price Prediction

# Property Listening

| No. of Rooms | House Size (sq ft) | Location   | Price |
|--------------|--------------------|------------|-------|
| 2            | 850                | Kathmandu  | 50000 |
| 3            | 1200               | Bhaktapur  | 75000 |
| 4            | 1500               | Lalitpur   | 100000 |
| 2            | 900                | Kathmandu  | 55000 |
| 5            | 1800               | Bhaktapur  | 120000 |
| 3            | 1100               | Lalitpur   | 70000 |

Location (Kathmandu, Bhaktapur, Lalitpur)

* The data store in a location is in categorical form(character)

Location = One Hot Encoding

# Property Listing
*  How One Hot Encoding work = > The data store in a location makes new column and
*  when kathmandu data come it store as a 1,aru ma 0
* when Bhaktapur data come it store as a 1, aru ma 0
* when Lalitpur data come it store as a 1, aru ma 0

| No. of Rooms | House Size (sq ft) | Location  | Price (NPR) | Kathmandu | Bhaktapur | Lalitpur |
| ------------ | ------------------ | --------- | ----------- | --------- | --------- | -------- |
| 2            | 850                | Kathmandu | 50000       | 1         | 0         | 0        |
| 3            | 1200               | Bhaktapur | 75000       | 0         | 1         | 0        |
| 4            | 1500               | Lalitpur  | 100000      | 0         | 0         | 1        |
| 2            | 900                | Kathmandu | 55000       | 1         | 0         | 0        |
| 5            | 1800               | Bhaktapur | 120000      | 0         | 1         | 0        |
| 3            | 1100               | Lalitpur  | 70000       | 0         | 0         | 1        |

# Advantages
* One hot encoding convert categorical data(character) into numerical data which is always in 1 and 0

# Disadvantages
* It Create spare matrix.(10 locations only takes 1 and 0 which lead to overfitting) ( Search on google spare matrix)
* 1000 categories (100 features). No of features increased, performance of model decreases
* i.e features means columns

In [ ]:
# import pandas and one hot encoder
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# create a dataframe with a single column of color categories
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [ ]:
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.dtypes

color    object
dtype: object

According to the above color column all data is in object that is categorical form

In [ ]:
## Create an instance of the OneHotEncoder,Note: OneHotEncoder() is a class. Hold on OneHotEncoder then see
ohe = OneHotEncoder()

In [ ]:
ohe.fit_transform(df[['color']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>
  * It means spare matrix banyo where 6 ota rows and 3 ota columns banyo.

In [ ]:
# convert spare matrix into array by using toaraay()
ohe.fit_transform(df[['color']]).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [ ]:
# fit the encoder to the dataframe and transform the category
encoded = ohe.fit_transform(df[['color']]).toarray()

In [ ]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [ ]:
# take above encoded data which is in 2D array, and take columns name
encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(['color'])) # get_feature_names_out is a function.Hold on get_feature_names_out                        )

In [ ]:
encoded_df  # column name is always in aplhabetical order i.e a,b,c so blue,green,red. Here,we can see now categorical(character is in numerical)

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [ ]:
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [ ]:
# By default NaN while concat
pd.concat([df, encoded_df])

   color  color_blue  color_green  color_red
0    red         NaN          NaN        NaN
1   blue         NaN          NaN        NaN
2  green         NaN          NaN        NaN
3  green         NaN          NaN        NaN
4    red         NaN          NaN        NaN
5   blue         NaN          NaN        NaN
0    NaN         0.0          0.0        1.0
1    NaN         1.0          0.0        0.0
2    NaN         0.0          1.0        0.0
3    NaN         0.0          1.0        0.0
4    NaN         0.0          0.0        1.0
5    NaN         1.0          0.0        0.0

In [ ]:
# Removing NaN above data by puting axis = 1
pd.concat([df, encoded_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

..........

In [ ]:
import seaborn as sns
df = sns.load_dataset('tips')

In [ ]:
df.shape

(244, 7)

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [ ]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [ ]:
encoder = OneHotEncoder()

In [ ]:
encoder.fit_transform(df[['time']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 244 stored elements and shape (244, 2)>

In [ ]:
encoder.fit_transform(df[['day']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 244 stored elements and shape (244, 4)>

In [ ]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [ ]:
encoded = encoder.fit_transform(df[['time']]).toarray()

In [ ]:
encoded

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [ ]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
# take above encode time data which is in 2D array, and take columns name
encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(['time']))

In [ ]:
encoded_df

     time_Dinner  time_Lunch
0            1.0         0.0
1            1.0         0.0
2            1.0         0.0
3            1.0         0.0
4            1.0         0.0
..           ...         ...
239          1.0         0.0
240          1.0         0.0
241          1.0         0.0
242          1.0         0.0
243          1.0         0.0

[244 rows x 2 columns]

# 2) Label and Ordinal Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
# Create dataframe
df = pd.DataFrame({
    'color': ['red','blue','green','green','blue','red']
})

In [ ]:
df

   color
0    red
1   blue
2  green
3  green
4   blue
5    red